### PR TITLE
Attribute Fixes

### LINKED ISSUE #158: Treesitter does not handle [private] alias
It seems the treesitter will error on a private alias. Using InspectTree I see the error, remove the private anno and fixed.
Example:

```
alias foo := bar
[private]
alias o := open
```

### LINKED ISSUE #176: Support rule groups
Currently, [rule groups](https://github.com/IndianBoy42/tree-sitter-just) are not supported and even produce a parse error, — breaking any highlighting based on it.

Example:

```just
[group('python')]
fmt:
    ruff format || true
```

Capture d’écran 2024-09-17 à 16 55 28

This is the output from Zed's AST using [jackTabsCode/zed-just](https://github.com/jackTabsCode/zed-just) which leverages tree-sitter-just.

(An example from the tree-sitter playground would have been more informative, but I cannot compile tree-sitter-just locally, I'll try again but platform specific issue it seems.)

### PR DESCRIPTION
**Pull request by kennyp**
## Changes
- Fix language detection when attribute has multiple arguments.
- Fix attributes on `alias`

## Related
- This is a follow-up to #177
- Fixes #158 
- Fixes #176

### CODE REVIEW

**Comment by kennyp** [comment]
Converting to draft while I verify some other things locally.

**Comment by kennyp** [comment]
Ready for review.

**Comment by tgross35** [comment]
Thanks! Could you add a test in `test/corpus/statements.txt`?

**Comment by kennyp** [comment]
@tgross35 good call. Tests have been added.

**Comment by tgross35** [comment]
Many thanks!

**Pull request merged**
