### PR TITLE
Allow spaces after shebang

### PR DESCRIPTION
**Pull request by alanpearce**
Unfortunately I wasn't able to run the npx-bundled tree-sitter on my system, but I verified it with my system's version and it worked fine.  This might mean some files need to be regenerated and unfortunately I won't be able to generate them in the same way.

Dennis Ritchie introduced shebangs to Version 8 Unix in 1980. An excerpt of his message, with formatting for clarity:

> To take advantage of this wonderful opportunity,
> put
>
>   `#! /bin/sh`
>
> at the left margin of the first line of your shell scripts.
> Blanks after ! are OK.  Use a complete pathname (no search is done).
> At the moment the whole line is restricted to 16 characters but
> this limit will be raised.

https://www.in-ulm.de/~mascheck/various/shebang/sys1.c.html

### CODE REVIEW

**Comment by tgross35** [comment]
Thank you for the patch! Did you run `just gen`? It looks like it doesn't like something but CI doesn't say exactly what (I just pushed a change that should give more information, you should get it if you rebase).

**Comment by alanpearce** [comment]
No, I didn't run `just gen`: as I mentioned, I could not get the version of tree-sitter installed via `npm` to work, so I had to use the version on my system. I had run all the commands that `just gen` runs, but my guess is slight differences in the version of tree-sitter led to the differences in output.

I managed to get set up on another machine and that's able to run the npm version just fine, so hopefully it should be fine now.

**Comment by tgross35** [comment]
Oh sorry, I completely skimmed over that. If CI doesn't pass here, I'll just fix it.

**Comment by tgross35** [comment]
Looks good now. Thank you for the fix!

**Pull request merged**
