### PR TITLE
Tidying

### PR DESCRIPTION
**Pull request by amaanq**
This is a pretty big PR, so I'll try to summarize what I've done in a few bullets. But, I'm hoping that this'll just complete the grammar and alleviates some pain points I'm sure you guys have had when trying to implement certain constructs.

- tidied up the grammar and scanner using eslint and clang-format respectively, as well as adding some doc comments to the grammar.
- removed unnecessary rules and fields, and renamed some that just better fit the standard way of doing stuff in tree-sitter, as well as hiding some noisy rules that don't need to be exposed
- adjusted how text is parsed by moving it to the scanner, it has also been fuzzed and works great
- reworked the queries, upstream and others will be moving towards the last-wins precedence, Neovim and Zed currently do this, and the CLI can do this as well with a flag argument, so it's better to stick to this precedence here as well.
- rework the style of pretty much every component to be more in-tune with how upstream grammars do it

Feedback appreciated, I'll get to adding actions n stuff in a bit, and I'd be happy to answer any questions/concerns anyone would have

cc @tgross35

### CODE REVIEW

**Comment by tgross35** [comment]
Highly appreciate the contribution, this looks great! I am out of town and away from a computer for the next couple days, but I will take a more thorough look once I’m back. I’ll probably be able to pull a few of these patches directly to slim down this PR.

Few quick notes:

- There are some changes, updated queries, and tests in the `next` branch (branch with lots of fixes but also the segfault problem) that may conflict. It looks like you may have pulled some from there. I’ll see what I can cherry pick from there to main, but this should definitely be run against the more complete tests from that branch.
- I’m very glad to hear that last wins is available via a flag! Didn’t know this was implemented yet
- The repo is currently formatted and linted with deno (`just ci-codestyle` to replicate). I don’t mind changing but want to keep double quotes for JS, since that’s what every other language in the repo uses. clang-format is a great addition!
- TS parse and highlight are already checked in CI (`just test-parse-highlight`) but maybe that could be expanded

Again thanks for this huge PR, I’ll do some testing when I get back.

**Comment by tgross35** [comment]
Might as well ask, what are the criteria for moving a grammar under the tree-sitter organization? I think the repo owner may have expressed interest in that at some point.

**Comment by amaanq** [comment]
I based it off master, I'll pull whatever's missing from `next` that fits in, especially the tests. I can adjust my eslint rule to use double quotes, I didn't notice the ci-codestyle rule, my bad.

Also, we aren't really accepting requests for grammars to be moved upstream, since there's too many languages that vary in maintainer and community size, the main criteria is really just how big and popular the language is. I don't think we'd ever move Just there, typically we just allow *bindings* to move in (most recently, csharp-tree-sitter)

**Comment by tgross35** [comment]
Finally getting a chance to work through these. 

- [x] 8c4e056 chore: formatting - added prettier and reapplied in #81
- [x] 232f390 fix: rework dependencies - reapplied in #82
- [ ] 09c3b3f chore: rename escapes
- [ ] d063751 chore: rename indented strings
- [ ] d170c5e fix: newlines after an escape
- [ ] d2f8a35 fix: hide noisy eol
- [ ] 10b0c23 fix: rewrite text, eol, and comment
- [ ] f4ad737 chore: remove noisy fields and rules
- [ ] 04a2f4e feat: add script for parsing upstream test files
- [ ] 8b683f3 refactor: move alternatives to their own rules
- [ ] e2c8358 fix: empty lines
- [ ] 9d7d572 fix: handle special newline cases better
- [ ] 6fd4516 fix: rewrite queries
- [ ] 3e4606f chore: generate
- [ ] 0572d8b chore: remove highlight tests for now
- [ ] cd471c0 fix(rust): allow the rust bindings to compile

**Comment by tgross35** [comment]
>     * reworked the queries, upstream and others will be moving towards the last-wins precedence, Neovim and Zed currently do this, and the CLI can do this as well with a flag argument, so it's better to stick to this precedence here as well.

@amaanq what flag is needed for this? I can't seem to find anything

**Comment by tgross35** [comment]
Alright, I have just about everything applied except the queries. You mentioned that the parser had been fuzzed - I am seeing some crashes in CI that I can't reproduce locally, e.g. https://github.com/IndianBoy42/tree-sitter-just/actions/runs/7958963921/job/21724921277#step:9:9. Any chance you could take a look? Had to make a few adjustments but I think it is pretty close to what you had.

A couple in case CI logs disappear:

```sh
Contents of fuzzer/failures/crash-d3aecbc6696a38f74c58a61efee206616d6e7daa:
8ZmQkG1lX2Ygc29tZV9mbigiLCBwYXJhbTIpCg==

Contents of fuzzer/failures/crash-de9105dd7138c3a6b49dbd70f3cdae86e3603eb2:
8pmQkN/F3fViYXIgOj0gImJcXCMA
```

There is a quick debug setup (need the latest pull), `echo 8pmQkN/F3fViYXIgOj0gImJcXCMA | base64 -D > a.just && just debug-run a.just` can run the files.

There are some multiline/nesting things to fix too https://github.com/IndianBoy42/tree-sitter-just/pull/109/files https://github.com/IndianBoy42/tree-sitter-just/blob/main/test/highlight/injections.just but other than that, these changes have been great!

**Comment by tgross35** [comment]
Great. I can't replicate the ubsan failures either on my local x86 machine or on a github codespace, which I would expect to be the same as the CI where I see the failures.

Probably safe to ignore, just need to run the CI fuzzer in docker or something so it is isolated and can pass.

**Comment by tgross35** [comment]
@amaanq I applied or addressed all the changes in this PR as tracked at https://github.com/IndianBoy42/tree-sitter-just/pull/79#issuecomment-1951482020, so I'm going to go ahead and close this.

Thank you for all the help! Let me know if you have other suggestions.

**Pull request closed without merging**
